# Generated by Django 5.0.3 on 2024-03-09 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_author_data_of_birth_alter_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 15, 26, 23, 738526, tzinfo=datetime.timezone.utc)),
        ),
    ]
