# Generated by Django 5.0.3 on 2024-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_author_data_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data_of_birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
